spring:
  application:
    name: restaurant
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/restaurant_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  key: fjnewjkqrfbjkeqwbflkjliwhwrnwbfiwbier